title: OSORI DB
description: Initial Github Pages for OSORI DB
theme: just-the-docs

url: https://osori-db.github.io

aux_links:
  Template Repository: https://github.com/osori-db/osori-db.github.io

plugins:
  - jekyll-multiple-languages-plugin

languages: ["en", "ko"]
exclude_from_localizations: ["javascript", "images", "css"]
defaultLang: en
languageNames:
  ko: Korean
  en: English
