title: OSORI
description: Github Page for OSORI
theme: just-the-docs
url: https://osori-db.github.io

color_scheme: dark_theme
logo: "/assets/images/ic_logo_osori.png"
favicon_ico: "/assets/images/favicon.ico"

plugins:
  - jekyll-multiple-languages-plugin

languages: ["en", "ko"]
exclude_from_localizations: ["javascript", "images", "css"]
defaultLang: en
languageNames:
  ko: Korean
  en: English
