name: Send email

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'test user argument'
        type: environment
        required: true
        default: g.tajonera

jobs:
  send-email:
    runs-on: ubuntu-latest
    env:
      USER: ${{inputs.name}}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.GMAIL_USERNAME}}
          password: ${{secrets.GMAIL_PASSWORD}}
          subject: Github Actions job result
          to: g.tajonera@samsung.com
          from: OSORI
          body: Hi $USER, workflow for ${{github.repository}} completed successfully!